# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-04 19:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='time',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
