# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-04 19:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_auto_20170304_1933'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='ip_addr',
        ),
        migrations.AlterField(
            model_name='item',
            name='time',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
    ]
