# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-15 00:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, default='empty.jpg', upload_to='images'),
        ),
    ]
